export const ENGINE_CONFIG = {
  // Effort parameters
  W_UP: 8,
  W_DOWN: 1.5,
  W_STEEP: 3,
  STEEP_DOWN_PCT: 0.15,
  STAIRS_MULT: 1.5,
  UPHILL_MIN_ASCENT_M: 10,
  UPHILL_GRADE_PCT: 0.05,
  UPHILL_MIN_STRETCH_M: 200,

  // Mode parameters
  SWITCH_PENALTY: 500,

  // Taxi parameters
  TAXI_MIN_LEG_M: 250,
  TAXI_SPEED_KMH: 18,
  TAXI_WAIT_MIN: 4,
  TAXI_BASE_FARE_KRW: 4800,
  TAXI_BASE_DIST_M: 1600,
  TAXI_PER_DIST_M: 131,
  TAXI_PER_FARE_KRW: 100,
  TAXI_ACCESS_WALK_M: 50,

  // Bus parameters
  BUS_ACCESS_MIN: 3,
  BUS_WAIT_MIN: 8,
  BUS_SPEED_KMH: 15,
  BUS_FARE_KRW: 1500,
  BUS_ACCESS_WALK_M: 300,

  // PM parameters
  PM_MAX_UP_GRADE_PCT: 3,
  PM_MAX_DOWN_GRADE_PCT: 10,
  PM_SPEED_KMH: 12,
  PM_UNLOCK_MIN: 2,
  PM_UNLOCK_KRW: 1000,
  PM_PER_MIN_KRW: 150,
  PM_ACCESS_WALK_M: 100,
  PM_EFFORT_FACTOR: 0.15,
};
